name: Crawler

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@main
    secrets:
      args: ${{ secrets.RELATON_CI_PAT }}
    with:
      commit-indexes: false
